# Generated by Django 5.1.4 on 2025-01-17 06:21

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=50, unique=True)),
                ('assigned_at', models.DateTimeField()),
                ('solved_at', models.DateTimeField(blank=True, null=True)),
                ('annotations', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200)),
                ('paragraph', ckeditor.fields.RichTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_type', models.CharField(choices=[('break1', 'Break 1'), ('break2', 'Break 2'), ('lunch', 'Lunch'), ('training', 'Training'), ('meeting', 'Meeting')], max_length=20)),
                ('aux_used', models.CharField(choices=[('timeout', 'TimeOut'), ('Other', 'Other'), ('training', 'Training'), ('Mentoring', 'DEP')], max_length=20)),
                ('in_time', models.DateTimeField()),
                ('out_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('value', models.TextField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='appnotenova.case')),
            ],
        ),
    ]
