# Generated by Django 5.1.4 on 2025-01-13 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnotenova', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_type', models.CharField(choices=[('lunch', 'Lunch Break'), ('break1', 'Break 1'), ('break2', 'Break 2'), ('personal', 'Personal Break'), ('meeting', 'Meeting'), ('training', 'Training'), ('other', 'Other')], max_length=20)),
                ('aux_used', models.BooleanField(default=False)),
                ('in_time', models.DateTimeField()),
                ('out_time', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='appnotenova.case')),
            ],
        ),
    ]
