# Generated by Django 5.1.4 on 2025-01-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnotenova', '0002_timetracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetracker',
            name='aux_used',
            field=models.BooleanField(choices=[('lunch', 'Time Out'), ('break1', 'Time Out'), ('break2', 'Time Out'), ('meeting', 'Other')], max_length=20),
        ),
    ]
