# Generated by Django 5.1.4 on 2025-01-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnotenova', '0003_alter_timetracker_aux_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetracker',
            name='case',
        ),
        migrations.AlterField(
            model_name='timetracker',
            name='aux_used',
            field=models.BooleanField(choices=[('break1', 'TimeOut'), ('break2', 'TimeOut'), ('lunch', 'TimeOutr'), ('Meeting', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='timetracker',
            name='break_type',
            field=models.CharField(choices=[('lunch', 'Lunch Break'), ('personal', 'Personal Break'), ('meeting', 'Meeting'), ('training', 'Training'), ('other', 'Other')], max_length=20),
        ),
    ]
