# Generated by Django 5.1.4 on 2025-01-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnotenova', '0004_remove_timetracker_case_alter_timetracker_aux_used_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetracker',
            name='aux_used',
            field=models.BooleanField(choices=[('timeout', 'TimeOut'), ('Other', 'Other'), ('training', 'Training')], max_length=20),
        ),
        migrations.AlterField(
            model_name='timetracker',
            name='break_type',
            field=models.CharField(choices=[('break1', 'Break 1'), ('break2', 'Break 2'), ('lunch', 'Lunch'), ('training', 'Training'), ('meeting', 'Meeting')], max_length=20),
        ),
    ]
